# General settings for the Windows 11 installation
[general]
# Specifies the edition of Windows 11 to be installed from the WIM file
Edition = "Windows 11 Pro"
# Path to the ISO file containing the Windows 11 installer
iso = "D:\\WimPatcher\\wimpatcher\\Win11.iso"
# List of drivers to install
drivers = [
    "C:\\drivers\\mydriver1.inf",
    "C:\\drivers\\mydriver2.inf",
    "C:\\drivers\\mydriver3.inf",
]
# List of Windows Updates to install during the Windows installation process
updates = ["KB5001330", "KB5001337", "MyUpdateFile.msu"]

# Specifies whether the following software should be installed
[supported-software]
"Dolphin Emulator" = true
"7zip" = true
"Discord" = false
"Discord Canary" = true

# Firefox Web Browser Installation Configuration
[software.firefox]
# Download link for the Firefox installer
installer = "https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US"
# Command-line parameters to customize the installation process.
# See https://firefox-source-docs.mozilla.org/browser/installer/windows/installer
parameters = ["/S", "/TaskbarShortcut=true"]
